fix: back to Fedora 45 with GNOME
Plasma keeps opening with black screen :/

diff --git a/system_files/usr/libexec/replace-fedora-flatpak b/system_files/usr/libexec/replace-fedora-flatpak
--- a/system_files/usr/libexec/replace-fedora-flatpak
+++ b/system_files/usr/libexec/replace-fedora-flatpak
@@ -28,12 +28,16 @@ for i in {1..10}; do
 done
 
 echo "Replacing Fedora Flatpaks with Flathub"
-mapfile -t TO_REPLACE < <(
-  flatpak list --app --columns=application,origin |
-  awk '$2 == "fedora" {print $1}'
-)
-/usr/bin/flatpak uninstall -y --noninteractive "${TO_REPLACE[@]}"
-/usr/bin/flatpak install -y --noninteractive flathub "${TO_REPLACE[@]}"
+TO_REPLACE=$(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
+
+for app in $TO_REPLACE; do
+  echo "Replacing $app with its Flathub version..."
+  /usr/bin/flatpak uninstall -y --noninteractive "$app" &>/dev/null </dev/null
+  if ! /usr/bin/flatpak install -y --noninteractive flathub "$app" &>/dev/null </dev/null; then
+    # Should ideally never be here
+    echo "$app cannot be found in Flathub!"
+  fi
+done
 
 echo "Removing flatpaks that were only from fedora flatpak"
 /usr/bin/flatpak list --system --columns=ref,origin |
